services:
  upload-file-app:
    image: upload-file-app
    container_name: upload-file-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      - rabbitmq
    volumes:
      - ./src/uploads:/app/src/uploads
      - ./src/uploads:/app/dist/uploads
    networks:
      - upload-file-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - upload-file-network

networks:
  upload-file-network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_logs:
